import accordionHowToPlay from './js/accordion.how_to_play.js';
import modalWindow from '/js/modal';
import './js/reviews';
import './js/faq';
import showGoogleBtn from './js/header.js';
import './js/gallery-swiper.js';
import './js/about_the_game_animation';
modalWindow();
accordionHowToPlay();
showGoogleBtn();
